### ISSUE TITLE
Feature Request: CLI Mode

### ISSUE THREAD

**Issue by magicaldave** [Yacoby/mw-mesh-gen#1]
Heya!

We'd like to use groundcover-generator at MOMW to make grass plugins in our CI. Is a CLI mode a feature you'd be willing to implement?

Edit:
If you're in the market for recommendations, I'm unsure how ini files are presently being parsed, but maybe boost::program_options would be nice here, or just sticking the necessary args into the ini file would also work.

**Comment by Yacoby** [comment]
Although some of the code is somewhat coupled to the UI, it shouldn't be much effort to add command line support and something I could do (although no promises on any timelines)

In terms of UX, I'd probably go with just supplying the arguments that the GUI has, mostly because it is the least effort to maintain. For example:

`mwgroundcover generate --configuration path/to/ini --plugin somedir/path/plugin.esp --plugin somedir/path/plugin2.esp --output somedir/path/output.esp`

**Comment by Yacoby** [comment]
There is a [basic CLI in this release](https://github.com/Yacoby/mw-groundcover-generator/releases) with limited testing. Note that for implementation simplicity the CLI is a different binary.
